### ISSUE TITLE
Template variable warning:

### ISSUE THREAD

**Issue by mattbruman** [jeremywillans/ha-rest980-roomba#31]
Having this error repeating over and over in my logs

`2021-08-30 10:34:56 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: list object has no element 1 when rendering '{% if state_attr('sensor.rest980', 'softwareVer') is defined %} {% set version = state_attr('sensor.rest980', 'softwareVer') %}
  {{ version.split('+')[1] }} 
{% else %}
  n-a
{% endif %}'`

**Comment by mattbruman** [comment]
For now I have commented out the softwareVer code and it has stopped the error

**Comment by jeremywillans** [comment]
Can you please share the output from sensor.rest980? specifically the softwareVer line.

**Comment by jeremywillans** [comment]
bump

**Comment by mattbruman** [comment]
Sorry had some issues with my Roomba and had to factory reset. I think I'm gonna just redo this whole component from scratch. I have a feeling my issue is because I disabled the features my 980 doesn't have like specific room cleaning and bin emptying.

**Comment by blakdog1978** [comment]
Good morning,
sorry my english but i get help from google ...
given the impossibility of robots to work in the dark I would like to be able to create an automation with lights, let me explain since on the phone app it is displayed in which room the robot is cleaning, I would like to be able to turn on the light automatically when the robot is in the room and consequently turn it off when he leaves it, do you think this is possible?
Thanks...

**Comment by jeremywillans** [comment]
This component relies on the data from rest980/dorita980 which does not seem to provide the current vacuumed/heading to the room like the app does. 😞 the closest you could get in the automation is to add a step to turn on all the light at the beginning and off again at the end, may not the best outcome however.
