### ISSUE TITLE
Card buttons stopped responding

### ISSUE THREAD

**Issue by whinis** [jeremywillans/ha-rest980-roomba#67]
A few updates ago the clean and empty bin (and seemingly other) buttons have stopped responding to any inputs both via mobile and via browser. As far as I can tell checking the networking tab in firefox no network request are firing off, however the card itself updates with the status.

**Comment by peluho** [comment]
Not sure if it is related, but since the latest update maybe before. For instance the Full Clean button stopped responding as well. I only can use the selective cleaning. I wonder what may happend, it was working perfectly.

thank you for your support.

Core 2024.4.3
Supervisor 2024.04.0
Frontend 20240404.2

I found also this error in the log

Logger: roombapy.remote_client
Source: /usr/local/lib/python3.12/site-packages/roombapy/remote_client.py:95
First occurred: 4:37:22 PM (150 occurrences)
Last logged: 5:38:09 PM

Can't connect to 192.168.3.28
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/roombapy/remote_client.py", line 93, in connect
    self._open_mqtt_connection()
  File "/usr/local/lib/python3.12/site-packages/roombapy/remote_client.py", line 117, in _open_mqtt_connection
    self.mqtt_client.connect(self.address, self.port)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by whinis** [comment]
For me its neither full clean nor dock. Right now I have resorted to an automation that calls the appropriate rest command. My understanding is the selective clean does the same.

**Comment by peluho** [comment]
@whinis Can you explain me a bit further how did you manage to sort it out with an automation? Not sure right now to be honest how to tackle this :(

**Comment by whinis** [comment]
```- service: rest_command.vacuum_action
    data_template:
      command: >
        {% set state = states('sensor.vacuum') %} {% if state== 'Ready' %} {%
        set command = 'start' %} {%else %} {% set command = 'stop' %} {% endif
        %}  {{command}}```

**Comment by whinis** [comment]
sorry, it didn't finish the command cause it was on the same level. Basically a rest command like this in the automation that a button triggers
Based on the robot attributes you can have the buttons do different things

**Comment by jeremywillans** [comment]
Sorry for the delay - I have fixed this in the HA frontend card

**Comment by whinis** [comment]
confirmed that this works again

**Comment by peluho** [comment]
Thank you @jeremywillans !
